shared:
  input:
    # [Required]
    jfrogTokenIntegration: tomjfrog_jfrog_io

artifactCleanup:
  metadata:
    # [Required]
    pipelineName: hpe_artifact_cleanup

    # [Optional] Default value: artifact_cleanup_property_bag
    propertyBagResourceName: hpe_artifact_cleanup_property_bag

    # [Optional] Default value: artifact_cleanup_cron_trigger
    cronTriggerResourceName: hpe_artifact_cleanup_cron_trigger

    # [Optional] Default value: artifact_cleanup_webhook
    artifactCleanupWebhookName: artifact_cleanup_webhook

  controls:
    # [Optional] When defined with enabled: true then new Cron will be setup. Default expression: 0 0 5 ? * 1
    cron:
      enabled: false
      expression: "*/3 * * * *"
    webhook:
      enabled: true

    # [Optional] List of comma separated Artifactory repo names for which jfrogTokenIntegration is provided.
    # Useful when using the pipeline with Cron.
    repos: "mavencentral-remote-cache"

    # [Optional] Defaults to true, if not provided
    dryRun: "true"

    # [Optional] Defaults to 1000, if not provided
    paceTimeMS: 1000

    # [Optional] Defaults to 10, if not provided
    maxRepos: 10

    # [Optional] Defaults to 10, if not provided
    maxArtifacts: 100


dockerCleanup:
  metadata:
    # [Required]
    pipelineName: hpe_docker_artifact_cleanup

    # [Optional] Default value: docker_cleanup_property_bag
    propertyBagResourceName: hpe_docker_cleanup_property_bag

    # [Optional] Default value: docker_cleanup_cron_trigger
    cronTriggerResourceName: hpe_docker_cleanup_cron_trigger

  controls:
    # [Optional] When defined with enabled: true then new Cron will be setup. Default expression: 0 0 5 ? * 1
    cron:
      enabled: false
      expression: "*/3 * * * *"

    # [Optional] List of comma separated Artifactory Docker repo names for which jfrogTokenIntegration is provided.
    # Useful when using the pipeline with Cron.
    repos: "petclinicmonolith-docker-dev-local"

    # [Optional] Defaults to true, if not provided
    dryRun: "true"

    # [Optional] Defaults to 1000, if not provided
    paceTimeMS: 1000

    # [Optional] Defaults to 10, if not provided
    maxRepos: 10

    # [Optional] Defaults to 10, if not provided
    maxArtifacts: 100